# Generated by Django 3.2.3 on 2021-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210530_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customers',
            name='password2',
            field=models.TextField(max_length=500),
        ),
    ]
